
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author u07740243132
 */
public class JDlgAgrUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgAgrUsuarios
     */
    public JDlgAgrUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de usuário");
        setLocationRelativeTo(null);
        jTxtAgrCodigo.setEnabled(false);
        jTxtAgrNomeCompleto.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jFmtAgrDataDeNascimento.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrApelido.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jCboAgrNivel.setEnabled(false);
        jPwfAgrSenha.setEnabled(false);
                jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);
    }
    
        public void habilitar(boolean valor){
        jTxtAgrNomeCompleto.setEnabled(valor);
        jFmtAgrCpf.setEnabled(valor);
        jFmtAgrDataDeNascimento.setEnabled(valor);
        jChbAgrAtivo.setEnabled(valor);
        jTxtAgrApelido.setEnabled(valor);
        jFmtAgrCpf.setEnabled(valor);
        jCboAgrNivel.setEnabled(valor);
        jPwfAgrSenha.setEnabled(valor);
        jBtnAgrCancelar.setEnabled(valor);
        jBtnAgrConfirmar.setEnabled(valor);        
        jBtnAgrIncluir.setEnabled(!valor);
        jBtnAgrAlterar.setEnabled(!valor);
        jBtnAgrExcluir.setEnabled(!valor);
        jBtnAgrPesquisar.setEnabled(!valor);
    }
    public void habilitar(){
        jTxtAgrNomeCompleto.setEnabled(true);
        jFmtAgrCpf.setEnabled(true);
        jFmtAgrDataDeNascimento.setEnabled(true);
        jChbAgrAtivo.setEnabled(true);
        jTxtAgrApelido.setEnabled(true);
        jFmtAgrCpf.setEnabled(true);
        jCboAgrNivel.setEnabled(true);
        jPwfAgrSenha.setEnabled(true);
        jBtnAgrCancelar.setEnabled(true);
        jBtnAgrConfirmar.setEnabled(true);        
        jBtnAgrIncluir.setEnabled(false);
        jBtnAgrAlterar.setEnabled(false);
        jBtnAgrExcluir.setEnabled(false);
        jBtnAgrPesquisar.setEnabled(false);
    }
    public void desabilitar(){
        jTxtAgrNomeCompleto.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jFmtAgrDataDeNascimento.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrApelido.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jCboAgrNivel.setEnabled(false);
        jPwfAgrSenha.setEnabled(false);
        jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);        
        jBtnAgrIncluir.setEnabled(true);
        jBtnAgrAlterar.setEnabled(true);
        jBtnAgrExcluir.setEnabled(true);
        jBtnAgrPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtAgrCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtAgrNomeCompleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtAgrApelido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtAgrCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtAgrDataDeNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCboAgrNivel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPwfAgrSenha = new javax.swing.JPasswordField();
        jChbAgrAtivo = new javax.swing.JCheckBox();
        jBtnAgrIncluir = new javax.swing.JButton();
        jBtnAgrAlterar = new javax.swing.JButton();
        jBtnAgrConfirmar = new javax.swing.JButton();
        jBtnAgrExcluir = new javax.swing.JButton();
        jBtnAgrCancelar = new javax.swing.JButton();
        jBtnAgrPesquisar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome Completo");

        jLabel3.setText("Apelido");

        jLabel4.setText("CPF");

        jLabel5.setText("Data De Nascimento");

        jLabel6.setText("Nível");

        jCboAgrNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Senha");

        jChbAgrAtivo.setText("Ativo");

        jBtnAgrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAgrIncluir.setText("Incluir");
        jBtnAgrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrIncluirActionPerformed(evt);
            }
        });

        jBtnAgrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAgrAlterar.setText("Alterar");
        jBtnAgrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrAlterarActionPerformed(evt);
            }
        });

        jBtnAgrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAgrConfirmar.setText("Confirmar");
        jBtnAgrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrConfirmarActionPerformed(evt);
            }
        });

        jBtnAgrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAgrExcluir.setText("Excluir");
        jBtnAgrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrExcluirActionPerformed(evt);
            }
        });

        jBtnAgrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAgrCancelar.setText("Cancelar");
        jBtnAgrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrCancelarActionPerformed(evt);
            }
        });

        jBtnAgrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAgrPesquisar.setText("Pesquisar");
        jBtnAgrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrPesquisarActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtAgrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAgrNomeCompleto))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtAgrApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtAgrCpf))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFmtAgrDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboAgrNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPwfAgrSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jChbAgrAtivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAgrIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAgrAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAgrExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAgrConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAgrCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAgrPesquisar)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtAgrDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboAgrNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfAgrSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAgrAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAgrIncluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrCancelar)
                        .addComponent(jBtnAgrPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrExcluir)
                        .addComponent(jBtnAgrConfirmar))
                    .addComponent(jBtnAgrAlterar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnAgrIncluirActionPerformed

    private void jBtnAgrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrAlterarActionPerformed
        habilitar();
    }//GEN-LAST:event_jBtnAgrAlterarActionPerformed

    private void jBtnAgrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrConfirmarActionPerformed
        desabilitar();
    }//GEN-LAST:event_jBtnAgrConfirmarActionPerformed

    private void jBtnAgrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrExcluirActionPerformed

    private void jBtnAgrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnAgrCancelarActionPerformed

    private void jBtnAgrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAgrUsuarios dialog = new JDlgAgrUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgrAlterar;
    private javax.swing.JButton jBtnAgrCancelar;
    private javax.swing.JButton jBtnAgrConfirmar;
    private javax.swing.JButton jBtnAgrExcluir;
    private javax.swing.JButton jBtnAgrIncluir;
    private javax.swing.JButton jBtnAgrPesquisar;
    private javax.swing.JComboBox<String> jCboAgrNivel;
    private javax.swing.JCheckBox jChbAgrAtivo;
    private javax.swing.JFormattedTextField jFmtAgrCpf;
    private javax.swing.JFormattedTextField jFmtAgrDataDeNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPwfAgrSenha;
    private javax.swing.JTextField jTxtAgrApelido;
    private javax.swing.JTextField jTxtAgrCodigo;
    private javax.swing.JTextField jTxtAgrNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
