
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author u07740243132
 */
public class JDlgAgrFornecedores extends javax.swing.JDialog {

    /**
     * Creates new form JDlgAgrFornecedores
     */
    public JDlgAgrFornecedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedores");
        setLocationRelativeTo(null);
        jTxtAgrNomeCompleto.setEnabled(false);
        jTxtAgrNomeSocial.setEnabled(false);
        jFmtAgrCelular.setEnabled(false);
        jTxtAgrInscricao.setEnabled(false);
        jTxtAgrEmpresa.setEnabled(false);
        jFmtAgrCnpj.setEnabled(false);
        jFmtAgrContato.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrInscricao.setEnabled(false);
        jFmtAgrEmail.setEnabled(false);
        jFmtAgrTelefone.setEnabled(false);
        jFmtAgrCelular.setEnabled(false);
        jFmtAgrCep.setEnabled(false);
        jTxtAgrEndereco.setEnabled(false);
        jTxtAgrBairro.setEnabled(false);
        jTxtAgrCidade.setEnabled(false);
        jCboAgrEstado.setEnabled(false);
        jTxtAgrNomeResponsavel.setEnabled(false);
                jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);
    }
    
    public void habilitar(boolean valor){
        jTxtAgrNomeCompleto.setEnabled(valor);
        jTxtAgrNomeSocial.setEnabled(valor);
        jFmtAgrCelular.setEnabled(valor);
        jTxtAgrInscricao.setEnabled(valor);
        jTxtAgrEmpresa.setEnabled(valor);
        jFmtAgrCnpj.setEnabled(valor);
        jFmtAgrContato.setEnabled(valor);
        jChbAgrAtivo.setEnabled(valor);
        jTxtAgrInscricao.setEnabled(valor);
        jFmtAgrEmail.setEnabled(valor);
        jFmtAgrTelefone.setEnabled(valor);
        jFmtAgrCelular.setEnabled(valor);
        jFmtAgrCep.setEnabled(valor);
        jTxtAgrEndereco.setEnabled(valor);
        jTxtAgrBairro.setEnabled(valor);
        jTxtAgrCidade.setEnabled(valor);
        jCboAgrEstado.setEnabled(valor);
        jTxtAgrNomeResponsavel.setEnabled(valor);
        jBtnAgrCancelar.setEnabled(valor);
        jBtnAgrConfirmar.setEnabled(valor);
        jBtnAgrIncluir.setEnabled(!valor);
        jBtnAgrAlterar.setEnabled(!valor);
        jBtnAgrExcluir.setEnabled(!valor);
        jBtnAgrPesquisar.setEnabled(!valor);
    }
    public void habilitar(){
        jTxtAgrNomeCompleto.setEnabled(true);
        jTxtAgrNomeSocial.setEnabled(true);
        jFmtAgrCelular.setEnabled(true);
        jTxtAgrInscricao.setEnabled(true);
        jTxtAgrEmpresa.setEnabled(true);
        jFmtAgrCnpj.setEnabled(true);
        jFmtAgrContato.setEnabled(true);
        jChbAgrAtivo.setEnabled(true);
        jTxtAgrInscricao.setEnabled(true);
        jFmtAgrEmail.setEnabled(true);
        jFmtAgrTelefone.setEnabled(true);
        jFmtAgrCelular.setEnabled(true);
        jFmtAgrCep.setEnabled(true);
        jTxtAgrEndereco.setEnabled(true);
        jTxtAgrBairro.setEnabled(true);
        jTxtAgrCidade.setEnabled(true);
        jCboAgrEstado.setEnabled(true);
        jTxtAgrNomeResponsavel.setEnabled(true);
        jBtnAgrCancelar.setEnabled(true);
        jBtnAgrConfirmar.setEnabled(true);        
        jBtnAgrIncluir.setEnabled(false);
        jBtnAgrAlterar.setEnabled(false);
        jBtnAgrExcluir.setEnabled(false);
        jBtnAgrPesquisar.setEnabled(false);
    }
    public void desabilitar(){
        jTxtAgrNomeCompleto.setEnabled(false);
        jTxtAgrNomeSocial.setEnabled(false);
        jFmtAgrCelular.setEnabled(false);
        jTxtAgrInscricao.setEnabled(false);
        jTxtAgrEmpresa.setEnabled(false);
        jFmtAgrCnpj.setEnabled(false);
        jFmtAgrContato.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrInscricao.setEnabled(false);
        jFmtAgrEmail.setEnabled(false);
        jFmtAgrTelefone.setEnabled(false);
        jFmtAgrCelular.setEnabled(false);
        jFmtAgrCep.setEnabled(false);
        jTxtAgrEndereco.setEnabled(false);
        jTxtAgrBairro.setEnabled(false);
        jTxtAgrCidade.setEnabled(false);
        jCboAgrEstado.setEnabled(false);
        jTxtAgrNomeResponsavel.setEnabled(false);
        jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);        
        jBtnAgrIncluir.setEnabled(true);
        jBtnAgrAlterar.setEnabled(true);
        jBtnAgrExcluir.setEnabled(true);
        jBtnAgrPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtAgrNomeCompleto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtAgrNomeSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtAgrCelular = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAgrInscricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtAgrEmpresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFmtAgrCnpj = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmtAgrContato = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFmtAgrEmail = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtAgrEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFmtAgrCep = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtAgrCidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtAgrBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCboAgrEstado = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jFmtAgrTelefone = new javax.swing.JFormattedTextField();
        jChbAgrAtivo = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jTxtAgrNomeResponsavel = new javax.swing.JTextField();
        jBtnAgrIncluir = new javax.swing.JButton();
        jBtnAgrAlterar = new javax.swing.JButton();
        jBtnAgrConfirmar = new javax.swing.JButton();
        jBtnAgrExcluir = new javax.swing.JButton();
        jBtnAgrCancelar = new javax.swing.JButton();
        jBtnAgrPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Nome Social");

        jLabel3.setText("Celular");

        jLabel4.setText("Inscrição");

        jLabel5.setText("Empresa");

        jLabel7.setText("CNPJ");

        jLabel8.setText("Contato");

        jLabel9.setText("Email");

        jLabel10.setText("Endereço");

        jLabel11.setText("CEP");

        jFmtAgrCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtAgrCepActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade");

        jLabel13.setText("Bairro");

        jLabel14.setText("Estado");

        jCboAgrEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCboAgrEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboAgrEstadoActionPerformed(evt);
            }
        });

        jLabel15.setText("Telefone");

        jChbAgrAtivo.setText("Ativo");

        jLabel16.setText("Nome Do Responsável Da Empresa");

        jTxtAgrNomeResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAgrNomeResponsavelActionPerformed(evt);
            }
        });

        jBtnAgrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAgrIncluir.setText("Incluir");
        jBtnAgrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrIncluirActionPerformed(evt);
            }
        });

        jBtnAgrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAgrAlterar.setText("Alterar");
        jBtnAgrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrAlterarActionPerformed(evt);
            }
        });

        jBtnAgrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAgrConfirmar.setText("Confirmar");
        jBtnAgrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrConfirmarActionPerformed(evt);
            }
        });

        jBtnAgrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAgrExcluir.setText("Excluir");
        jBtnAgrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrExcluirActionPerformed(evt);
            }
        });

        jBtnAgrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAgrCancelar.setText("Cancelar");
        jBtnAgrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrCancelarActionPerformed(evt);
            }
        });

        jBtnAgrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAgrPesquisar.setText("Pesquisar");
        jBtnAgrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtAgrNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAgrNomeSocial))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtAgrEndereco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFmtAgrCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addComponent(jFmtAgrCelular, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jTxtAgrInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                        .addComponent(jFmtAgrContato)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(249, 249, 249)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(179, 179, 179)
                                    .addComponent(jLabel8))))
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAgrCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAgrBairro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAgrEmpresa)
                    .addComponent(jFmtAgrEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel15)))
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboAgrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtAgrTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(jFmtAgrCep)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtAgrNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChbAgrAtivo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBtnAgrIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrPesquisar)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrNomeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtAgrCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtAgrCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboAgrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAgrAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrCancelar)
                        .addComponent(jBtnAgrPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrExcluir)
                        .addComponent(jBtnAgrConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrIncluir)
                        .addComponent(jBtnAgrAlterar)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboAgrEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboAgrEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboAgrEstadoActionPerformed

    private void jTxtAgrNomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAgrNomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAgrNomeResponsavelActionPerformed

    private void jBtnAgrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnAgrIncluirActionPerformed

    private void jBtnAgrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrAlterarActionPerformed
        habilitar();
    }//GEN-LAST:event_jBtnAgrAlterarActionPerformed

    private void jBtnAgrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrConfirmarActionPerformed
        desabilitar();
    }//GEN-LAST:event_jBtnAgrConfirmarActionPerformed

    private void jBtnAgrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrExcluirActionPerformed

    private void jBtnAgrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnAgrCancelarActionPerformed

    private void jBtnAgrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrPesquisarActionPerformed

    private void jFmtAgrCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtAgrCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtAgrCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAgrFornecedores dialog = new JDlgAgrFornecedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgrAlterar;
    private javax.swing.JButton jBtnAgrCancelar;
    private javax.swing.JButton jBtnAgrConfirmar;
    private javax.swing.JButton jBtnAgrExcluir;
    private javax.swing.JButton jBtnAgrIncluir;
    private javax.swing.JButton jBtnAgrPesquisar;
    private javax.swing.JComboBox<String> jCboAgrEstado;
    private javax.swing.JCheckBox jChbAgrAtivo;
    private javax.swing.JFormattedTextField jFmtAgrCelular;
    private javax.swing.JFormattedTextField jFmtAgrCep;
    private javax.swing.JFormattedTextField jFmtAgrCnpj;
    private javax.swing.JFormattedTextField jFmtAgrContato;
    private javax.swing.JFormattedTextField jFmtAgrEmail;
    private javax.swing.JFormattedTextField jFmtAgrTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtAgrBairro;
    private javax.swing.JTextField jTxtAgrCidade;
    private javax.swing.JTextField jTxtAgrEmpresa;
    private javax.swing.JTextField jTxtAgrEndereco;
    private javax.swing.JTextField jTxtAgrInscricao;
    private javax.swing.JTextField jTxtAgrNomeCompleto;
    private javax.swing.JTextField jTxtAgrNomeResponsavel;
    private javax.swing.JTextField jTxtAgrNomeSocial;
    // End of variables declaration//GEN-END:variables
}
