
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author u07740243132
 */
public class JDlgAgrVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgAgrVendedor
     */
    public JDlgAgrVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedores");
        setLocationRelativeTo(null);
        jTxtAgrNomeCompleto.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jFmtAgrDataDeNascimento.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrCelular.setEnabled(false);
        jFmtAgrEmail.setEnabled(false);        
        jTxtAgrEndereco.setEnabled(false);
        jTxtAgrCidade.setEnabled(false);
        jCboAgrEstado.setEnabled(false);
                jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);
    }
    
        public void habilitar(boolean valor){
        jTxtAgrNomeCompleto.setEnabled(valor);
        jFmtAgrCpf.setEnabled(valor);
        jFmtAgrDataDeNascimento.setEnabled(valor);
        jChbAgrAtivo.setEnabled(valor);
        jTxtAgrCelular.setEnabled(valor);
        jFmtAgrEmail.setEnabled(valor);        
        jTxtAgrEndereco.setEnabled(valor);
        jTxtAgrCidade.setEnabled(valor);
        jCboAgrEstado.setEnabled(valor);
        jBtnAgrCancelar.setEnabled(valor);
        jBtnAgrConfirmar.setEnabled(valor);
        
        jBtnAgrIncluir.setEnabled(!valor);
        jBtnAgrAlterar.setEnabled(!valor);
        jBtnAgrExcluir.setEnabled(!valor);
        jBtnAgrPesquisar.setEnabled(!valor);
    }
    public void habilitar(){
        jTxtAgrNomeCompleto.setEnabled(true);
        jFmtAgrCpf.setEnabled(true);
        jFmtAgrDataDeNascimento.setEnabled(true);
        jChbAgrAtivo.setEnabled(true);
        jTxtAgrCelular.setEnabled(true);
        jFmtAgrEmail.setEnabled(true);        
        jTxtAgrEndereco.setEnabled(true);
        jTxtAgrCidade.setEnabled(true);
        jCboAgrEstado.setEnabled(true);
        jBtnAgrCancelar.setEnabled(true);
        jBtnAgrConfirmar.setEnabled(true);        
        jBtnAgrIncluir.setEnabled(false);
        jBtnAgrAlterar.setEnabled(false);
        jBtnAgrExcluir.setEnabled(false);
        jBtnAgrPesquisar.setEnabled(false);
    }
    public void desabilitar(){
        jTxtAgrNomeCompleto.setEnabled(false);
        jFmtAgrCpf.setEnabled(false);
        jFmtAgrDataDeNascimento.setEnabled(false);
        jChbAgrAtivo.setEnabled(false);
        jTxtAgrCelular.setEnabled(false);
        jFmtAgrEmail.setEnabled(false);        
        jTxtAgrEndereco.setEnabled(false);
        jTxtAgrCidade.setEnabled(false);
        jCboAgrEstado.setEnabled(false);
        jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);        
        jBtnAgrIncluir.setEnabled(true);
        jBtnAgrAlterar.setEnabled(true);
        jBtnAgrExcluir.setEnabled(true);
        jBtnAgrPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtAgrNomeCompleto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtAgrDataDeNascimento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtAgrCelular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtAgrEmail = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtAgrCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtAgrEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtAgrCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCboAgrEstado = new javax.swing.JComboBox<>();
        jChbAgrAtivo = new javax.swing.JCheckBox();
        jBtnAgrIncluir = new javax.swing.JButton();
        jBtnAgrAlterar = new javax.swing.JButton();
        jBtnAgrConfirmar = new javax.swing.JButton();
        jBtnAgrExcluir = new javax.swing.JButton();
        jBtnAgrCancelar = new javax.swing.JButton();
        jBtnAgrPesquisar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Data De Nascimento");

        jLabel3.setText("Celular");

        jLabel4.setText("Email");

        jLabel5.setText("CPF");

        jFmtAgrCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtAgrCpfActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço");

        jLabel7.setText("Cidade");

        jLabel8.setText("Estado");

        jCboAgrEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jChbAgrAtivo.setText("Ativo");

        jBtnAgrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAgrIncluir.setText("Incluir");
        jBtnAgrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrIncluirActionPerformed(evt);
            }
        });

        jBtnAgrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAgrAlterar.setText("Alterar");
        jBtnAgrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrAlterarActionPerformed(evt);
            }
        });

        jBtnAgrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAgrConfirmar.setText("Confirmar");
        jBtnAgrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrConfirmarActionPerformed(evt);
            }
        });

        jBtnAgrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAgrExcluir.setText("Excluir");
        jBtnAgrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrExcluirActionPerformed(evt);
            }
        });

        jBtnAgrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAgrCancelar.setText("Cancelar");
        jBtnAgrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrCancelarActionPerformed(evt);
            }
        });

        jBtnAgrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAgrPesquisar.setText("Pesquisar");
        jBtnAgrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtAgrCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtAgrEmail))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtAgrNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1))
                    .addComponent(jFmtAgrDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addComponent(jFmtAgrCpf)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel4))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboAgrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jChbAgrAtivo)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAgrIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAgrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addComponent(jTxtAgrCidade)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAgrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboAgrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAgrAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrCancelar)
                        .addComponent(jBtnAgrPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrExcluir)
                        .addComponent(jBtnAgrConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrIncluir)
                        .addComponent(jBtnAgrAlterar)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtAgrCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtAgrCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtAgrCpfActionPerformed

    private void jBtnAgrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnAgrIncluirActionPerformed

    private void jBtnAgrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrAlterarActionPerformed
        habilitar();
    }//GEN-LAST:event_jBtnAgrAlterarActionPerformed

    private void jBtnAgrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrConfirmarActionPerformed
        desabilitar();
    }//GEN-LAST:event_jBtnAgrConfirmarActionPerformed

    private void jBtnAgrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrExcluirActionPerformed

    private void jBtnAgrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnAgrCancelarActionPerformed

    private void jBtnAgrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAgrVendedor dialog = new JDlgAgrVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgrAlterar;
    private javax.swing.JButton jBtnAgrCancelar;
    private javax.swing.JButton jBtnAgrConfirmar;
    private javax.swing.JButton jBtnAgrExcluir;
    private javax.swing.JButton jBtnAgrIncluir;
    private javax.swing.JButton jBtnAgrPesquisar;
    private javax.swing.JComboBox<String> jCboAgrEstado;
    private javax.swing.JCheckBox jChbAgrAtivo;
    private javax.swing.JFormattedTextField jFmtAgrCpf;
    private javax.swing.JFormattedTextField jFmtAgrDataDeNascimento;
    private javax.swing.JFormattedTextField jFmtAgrEmail;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtAgrCelular;
    private javax.swing.JTextField jTxtAgrCidade;
    private javax.swing.JTextField jTxtAgrEndereco;
    private javax.swing.JTextField jTxtAgrNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
