
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author u07740243132
 */
public class JDlgAgrProdutos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgAgrProdutos
     */
    public JDlgAgrProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de produtos");
        setLocationRelativeTo(null);
        jTxtAgrTitulo.setEnabled(false);
        jTxtAgrPlataforma.setEnabled(false);
        jTxtAgrGenero.setEnabled(false);
        jTxtAgrPreco.setEnabled(false);
        jTxtAgrAnoDeLancamento.setEnabled(false);
                jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);
    }
    
        public void habilitar(boolean valor){
        jTxtAgrTitulo.setEnabled(valor);
        jTxtAgrPlataforma.setEnabled(valor);
        jTxtAgrGenero.setEnabled(valor);
        jTxtAgrPreco.setEnabled(valor);
        jTxtAgrAnoDeLancamento.setEnabled(valor);
        jBtnAgrCancelar.setEnabled(valor);
        jBtnAgrConfirmar.setEnabled(valor);        
        jBtnAgrIncluir.setEnabled(!valor);
        jBtnAgrAlterar.setEnabled(!valor);
        jBtnAgrExcluir.setEnabled(!valor);
        jBtnAgrPesquisar.setEnabled(!valor);
    }
    public void habilitar(){
        jTxtAgrTitulo.setEnabled(true);
        jTxtAgrPlataforma.setEnabled(true);
        jTxtAgrGenero.setEnabled(true);
        jTxtAgrPreco.setEnabled(true);
        jTxtAgrAnoDeLancamento.setEnabled(true);
        jBtnAgrCancelar.setEnabled(true);
        jBtnAgrConfirmar.setEnabled(true);        
        jBtnAgrIncluir.setEnabled(false);
        jBtnAgrAlterar.setEnabled(false);
        jBtnAgrExcluir.setEnabled(false);
        jBtnAgrPesquisar.setEnabled(false);
    }
    public void desabilitar(){
        jTxtAgrTitulo.setEnabled(false);
        jTxtAgrPlataforma.setEnabled(false);
        jTxtAgrGenero.setEnabled(false);
        jTxtAgrPreco.setEnabled(false);
        jTxtAgrAnoDeLancamento.setEnabled(false);
        jBtnAgrCancelar.setEnabled(false);
        jBtnAgrConfirmar.setEnabled(false);
        
        jBtnAgrIncluir.setEnabled(true);
        jBtnAgrAlterar.setEnabled(true);
        jBtnAgrExcluir.setEnabled(true);
        jBtnAgrPesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtAgrTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtAgrPlataforma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtAgrGenero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAgrPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtAgrAnoDeLancamento = new javax.swing.JTextField();
        jBtnAgrIncluir = new javax.swing.JButton();
        jBtnAgrAlterar = new javax.swing.JButton();
        jBtnAgrConfirmar = new javax.swing.JButton();
        jBtnAgrExcluir = new javax.swing.JButton();
        jBtnAgrCancelar = new javax.swing.JButton();
        jBtnAgrPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Título");

        jLabel2.setText("Plataforma");

        jLabel3.setText("Gênero");

        jLabel4.setText("Preço");

        jLabel5.setText("Ano De Lançamento");

        jBtnAgrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAgrIncluir.setText("Incluir");
        jBtnAgrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrIncluirActionPerformed(evt);
            }
        });

        jBtnAgrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAgrAlterar.setText("Alterar");
        jBtnAgrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrAlterarActionPerformed(evt);
            }
        });

        jBtnAgrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAgrConfirmar.setText("Confirmar");
        jBtnAgrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrConfirmarActionPerformed(evt);
            }
        });

        jBtnAgrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAgrExcluir.setText("Excluir");
        jBtnAgrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrExcluirActionPerformed(evt);
            }
        });

        jBtnAgrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAgrCancelar.setText("Cancelar");
        jBtnAgrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrCancelarActionPerformed(evt);
            }
        });

        jBtnAgrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAgrPesquisar.setText("Pesquisar");
        jBtnAgrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgrPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnAgrIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgrCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgrPesquisar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAgrTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addComponent(jTxtAgrPlataforma)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtAgrGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAgrPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addComponent(jTxtAgrAnoDeLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgrGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAgrAnoDeLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrCancelar)
                        .addComponent(jBtnAgrPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrExcluir)
                        .addComponent(jBtnAgrConfirmar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgrIncluir)
                        .addComponent(jBtnAgrAlterar)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrIncluirActionPerformed
        //habilitar();
        habilitar(true);
    }//GEN-LAST:event_jBtnAgrIncluirActionPerformed

    private void jBtnAgrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrAlterarActionPerformed
        habilitar();
    }//GEN-LAST:event_jBtnAgrAlterarActionPerformed

    private void jBtnAgrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrConfirmarActionPerformed
        desabilitar();
    }//GEN-LAST:event_jBtnAgrConfirmarActionPerformed

    private void jBtnAgrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrExcluirActionPerformed
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrExcluirActionPerformed

    private void jBtnAgrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrCancelarActionPerformed
        //desabilitar();
        habilitar(false);
    }//GEN-LAST:event_jBtnAgrCancelarActionPerformed

    private void jBtnAgrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgrPesquisarActionPerformed
        JOptionPane.showInputDialog(null, "Entre com a chave primária");          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAgrPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAgrProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAgrProdutos dialog = new JDlgAgrProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgrAlterar;
    private javax.swing.JButton jBtnAgrCancelar;
    private javax.swing.JButton jBtnAgrConfirmar;
    private javax.swing.JButton jBtnAgrExcluir;
    private javax.swing.JButton jBtnAgrIncluir;
    private javax.swing.JButton jBtnAgrPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtAgrAnoDeLancamento;
    private javax.swing.JTextField jTxtAgrGenero;
    private javax.swing.JTextField jTxtAgrPlataforma;
    private javax.swing.JTextField jTxtAgrPreco;
    private javax.swing.JTextField jTxtAgrTitulo;
    // End of variables declaration//GEN-END:variables
}
