/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author u07740243132
 */
public class JFrmAgrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAgrPrincipal
     */
    public JFrmAgrPrincipal() {
        initComponents();
        setTitle("Sistema Ana Roriz");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuAgrCadastro = new javax.swing.JMenu();
        jMnuAgrUsuarios = new javax.swing.JMenuItem();
        jMnuAgrClientes = new javax.swing.JMenuItem();
        jMnuAgrFornecedores = new javax.swing.JMenuItem();
        jMnuAgrProdutos = new javax.swing.JMenuItem();
        jMnuAgrVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuAgrSair = new javax.swing.JMenuItem();
        jMnuAgrMovimentos = new javax.swing.JMenu();
        jMnuAgrCompras = new javax.swing.JMenuItem();
        jMnuAgrVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuAgrCadastro.setMnemonic('C');
        jMnuAgrCadastro.setText("Cadastros");
        jMnuAgrCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrCadastroActionPerformed(evt);
            }
        });

        jMnuAgrUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuAgrUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-24.png"))); // NOI18N
        jMnuAgrUsuarios.setMnemonic('U');
        jMnuAgrUsuarios.setText("Usuários");
        jMnuAgrUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrUsuariosActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrUsuarios);

        jMnuAgrClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuAgrClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuAgrClientes.setMnemonic('C');
        jMnuAgrClientes.setText("Clientes");
        jMnuAgrClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrClientesActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrClientes);

        jMnuAgrFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuAgrFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-24.png"))); // NOI18N
        jMnuAgrFornecedores.setMnemonic('F');
        jMnuAgrFornecedores.setText("Fornecedores");
        jMnuAgrFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrFornecedoresActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrFornecedores);

        jMnuAgrProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuAgrProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-produtos-24.png"))); // NOI18N
        jMnuAgrProdutos.setMnemonic('P');
        jMnuAgrProdutos.setText("Produtos");
        jMnuAgrProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrProdutosActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrProdutos);

        jMnuAgrVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuAgrVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-vendedor-24.png"))); // NOI18N
        jMnuAgrVendedor.setMnemonic('V');
        jMnuAgrVendedor.setText("Vendedor");
        jMnuAgrVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrVendedorActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrVendedor);
        jMnuAgrCadastro.add(jSeparator1);

        jMnuAgrSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuAgrSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuAgrSair.setMnemonic('S');
        jMnuAgrSair.setText("Sair");
        jMnuAgrSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrSairActionPerformed(evt);
            }
        });
        jMnuAgrCadastro.add(jMnuAgrSair);

        jMenuBar1.add(jMnuAgrCadastro);

        jMnuAgrMovimentos.setMnemonic('M');
        jMnuAgrMovimentos.setText("Movimentos");

        jMnuAgrCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuAgrCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-compra-24.png"))); // NOI18N
        jMnuAgrCompras.setMnemonic('C');
        jMnuAgrCompras.setText("Compras");
        jMnuAgrCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrComprasActionPerformed(evt);
            }
        });
        jMnuAgrMovimentos.add(jMnuAgrCompras);

        jMnuAgrVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuAgrVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-venda-24.png"))); // NOI18N
        jMnuAgrVendas.setMnemonic('V');
        jMnuAgrVendas.setText("Vendas");
        jMnuAgrVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAgrVendasActionPerformed(evt);
            }
        });
        jMnuAgrMovimentos.add(jMnuAgrVendas);

        jMenuBar1.add(jMnuAgrMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuAgrCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuAgrCadastroActionPerformed

    private void jMnuAgrProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrProdutosActionPerformed
        // TODO add your handling code here:
        JDlgAgrProdutos jDlgAgrProdutos = new JDlgAgrProdutos(null, true);
        jDlgAgrProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuAgrProdutosActionPerformed

    private void jMnuAgrSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuAgrSairActionPerformed

    private void jMnuAgrVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrVendedorActionPerformed
        // TODO add your handling code here:
        JDlgAgrVendedor jDlgAgrVendedor = new JDlgAgrVendedor(null, true);
        jDlgAgrVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuAgrVendedorActionPerformed

    private void jMnuAgrUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgAgrUsuarios jDlgAgrUsuarios = new JDlgAgrUsuarios(null, true);
        jDlgAgrUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jMnuAgrUsuariosActionPerformed

    private void jMnuAgrClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrClientesActionPerformed
        // TODO add your handling code here:
        JDlgAgrClientes jDlgAgrClientes = new JDlgAgrClientes(null, true);
        jDlgAgrClientes.setVisible(true);
    }//GEN-LAST:event_jMnuAgrClientesActionPerformed

    private void jMnuAgrFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrFornecedoresActionPerformed
        // TODO add your handling code here:
        JDlgAgrFornecedores jDlgAgrFornecedores = new JDlgAgrFornecedores(null, true);
        jDlgAgrFornecedores.setVisible(true);
    }//GEN-LAST:event_jMnuAgrFornecedoresActionPerformed

    private void jMnuAgrComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuAgrComprasActionPerformed

    private void jMnuAgrVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAgrVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuAgrVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAgrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAgrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAgrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAgrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAgrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuAgrCadastro;
    private javax.swing.JMenuItem jMnuAgrClientes;
    private javax.swing.JMenuItem jMnuAgrCompras;
    private javax.swing.JMenuItem jMnuAgrFornecedores;
    private javax.swing.JMenu jMnuAgrMovimentos;
    private javax.swing.JMenuItem jMnuAgrProdutos;
    private javax.swing.JMenuItem jMnuAgrSair;
    private javax.swing.JMenuItem jMnuAgrUsuarios;
    private javax.swing.JMenuItem jMnuAgrVendas;
    private javax.swing.JMenuItem jMnuAgrVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
